services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.0-alpine-latest
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - zabbix-mysql
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.0-alpine-latest
    container_name: zabbix-web
    restart: unless-stopped
    ports:
      - "${ZABBIX_EXTERNAL_PORT}:8080"
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Moscow
    depends_on:
      - zabbix-server
      - zabbix-mysql
    networks:
      - zabbix-net

  zabbix-mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - zabbix-mysql-data:/var/lib/mysql
    networks:
      - zabbix-net
    ports:
      - "${ZABBIX_MYSQL_EXTERNAL_PORT}:3306"

  zabbix-agent:
    image: zabbix/zabbix-agent:6.0-alpine-latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    networks:
      - zabbix-net

volumes:
  zabbix-mysql-data:

networks:
  zabbix-net:
    driver: bridge
